### ISSUE TITLE
Application Error: Server-side Exception Occurs on Button Click

### ISSUE THREAD

**Issue by masabinhok** [max-programming/hacktoberfest-projects#215] opened 2024-10-01 12:13 UTC
**Title**: Application Error: Server-side Exception Occurs on Button Click

**Description**:
When I click on certain buttons that should redirect to different pages (e.g., programming language names), the application throws an error. The error message displayed is:

```
Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 2038395936
```

**Steps to Reproduce**:
1. Go to the webpage.
2. Click on any of the buttons that are supposed to redirect to specific pages (e.g., programming languages).
3. Observe the error message instead of being redirected.

**Expected Behavior**:
Clicking on the buttons should redirect to the appropriate pages without any errors.

**Actual Behavior**:
The page throws a server-side error with the message mentioned above.
https://github.com/user-attachments/assets/b6ce6222-4e67-48f3-bf4b-ffb081fb02d0

**Additional Context**:
- The issue seems to be server-side, as the error message suggests checking the server logs for more details.
- Digest code: `2038395936`.

**Possible Cause**:
There might be an issue in handling requests or routing on the server-side. It's also possible that certain backend services or APIs are not functioning as expected.

---

**Comment by max-programming** [comment] 2024-10-01 12:34
Thanks for the detailed explanation @masabinhok 

The problem was that on Vercel the Node.js version was 20 and I used the `.toSorted` array method.

Now fixed

**Closed by max-programming** 2024-10-01 12:34 UTC

**Comment by Prakharpan-dey** [comment] 2024-10-01 12:51
@max-programming Hey i think the issue is still there . 
When i select Dart as the programming language and select Recently Updated . It shows the same error .
Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 3695861736

**Comment by max-programming** [comment] 2024-10-01 13:48
@Prakharpan-dey I checked that one, pushed another fix just now
